/**
 * Space Resource Exchange – Market Data & Resource Definitions
 */

const RESOURCES = [
  {
    id: "lunar-ice",
    name: "Lunar Ice (Water)",
    symbol: "LNR-H2O",
    category: "Volatiles",
    unit: "ton",
    spotPrice: 450,
    description:
      "Polar-crater water ice. Feedstock for life support, electrolytic hydrogen/oxygen rocket propellant.",
    icon: "❄️",
    color: "#60a5fa",
    change24h: 2.4,
    volume24h: 1240,
  },
  {
    id: "helium3",
    name: "Helium-3",
    symbol: "He-3",
    category: "Fusion Fuels",
    unit: "kg",
    spotPrice: 3000000,
    description:
      "Rare lunar regolith isotope. Primary fuel for aneutronic D-He3 fusion reactors.",
    icon: "⚛️",
    color: "#f59e0b",
    change24h: 0.8,
    volume24h: 0.012,
  },
  {
    id: "platinum-group",
    name: "Platinum Group Metals",
    symbol: "PGM",
    category: "Precious Metals",
    unit: "oz",
    spotPrice: 28000,
    description:
      "Asteroid-sourced platinum, palladium, iridium, osmium. Industrial catalysts & electronics.",
    icon: "🔩",
    color: "#a78bfa",
    change24h: -1.2,
    volume24h: 340,
  },
  {
    id: "rare-earth",
    name: "Rare Earth Elements",
    symbol: "REE",
    category: "Industrial Metals",
    unit: "kg",
    spotPrice: 120,
    description:
      "Neodymium, dysprosium, europium etc. Essential for magnets, batteries and displays.",
    icon: "🧲",
    color: "#34d399",
    change24h: 3.1,
    volume24h: 8900,
  },
  {
    id: "iron-nickel",
    name: "Iron / Nickel Alloy",
    symbol: "FE-NI",
    category: "Industrial Metals",
    unit: "ton",
    spotPrice: 85,
    description:
      "M-type asteroid iron-nickel. Structural material for in-space manufacturing.",
    icon: "🏗️",
    color: "#9ca3af",
    change24h: -0.3,
    volume24h: 52000,
  },
  {
    id: "silicon",
    name: "Silicon",
    symbol: "SI",
    category: "Industrial Metals",
    unit: "ton",
    spotPrice: 1200,
    description:
      "High-purity silicon from S-type asteroids. Solar panel and semiconductor feedstock.",
    icon: "💠",
    color: "#38bdf8",
    change24h: 1.7,
    volume24h: 3200,
  },
  {
    id: "titanium",
    name: "Titanium",
    symbol: "TI",
    category: "Aerospace Metals",
    unit: "ton",
    spotPrice: 11000,
    description:
      "Lightweight structural metal from lunar and asteroid sources.",
    icon: "🚀",
    color: "#f472b6",
    change24h: 0.5,
    volume24h: 780,
  },
  {
    id: "regolith",
    name: "Lunar Regolith",
    symbol: "REG",
    category: "Construction",
    unit: "ton",
    spotPrice: 10000,
    description:
      "Bulk surface material. Radiation shielding, sintered bricks, 3-D print feedstock.",
    icon: "🌑",
    color: "#d1d5db",
    change24h: 0.0,
    volume24h: 120000,
  },
  {
    id: "thorium",
    name: "Thorium",
    symbol: "TH",
    category: "Nuclear Fuels",
    unit: "kg",
    spotPrice: 40,
    description:
      "Fertile nuclear material for thorium MSR reactors. Found in lunar KREEP terrain.",
    icon: "☢️",
    color: "#fde68a",
    change24h: -0.6,
    volume24h: 5600,
  },
  {
    id: "carbonaceous",
    name: "Carbonaceous Material",
    symbol: "C-ORG",
    category: "Organics",
    unit: "kg",
    spotPrice: 2500,
    description:
      "C-type asteroid organics: complex hydrocarbons, amino acid precursors, kerogen.",
    icon: "🌑",
    color: "#6b7280",
    change24h: 1.1,
    volume24h: 420,
  },
];

const CATEGORIES = [...new Set(RESOURCES.map((r) => r.category))];

// Pre-seeded open contracts visible to all users
const SEED_CONTRACTS = [
  {
    id: "c001",
    resourceId: "lunar-ice",
    type: "CALL",
    strikePrice: 500,
    quantity: 100,
    premium: 18,
    expiry: "2026-09-30",
    seller: "0xAbCd...1234",
    status: "OPEN",
    created: "2026-04-01",
  },
  {
    id: "c002",
    resourceId: "helium3",
    type: "CALL",
    strikePrice: 3100000,
    quantity: 0.5,
    premium: 45000,
    expiry: "2026-12-31",
    seller: "0xDeF0...5678",
    status: "OPEN",
    created: "2026-03-28",
  },
  {
    id: "c003",
    resourceId: "platinum-group",
    type: "PUT",
    strikePrice: 27000,
    quantity: 20,
    premium: 900,
    expiry: "2026-08-15",
    seller: "0x1122...AABB",
    status: "OPEN",
    created: "2026-04-02",
  },
  {
    id: "c004",
    resourceId: "rare-earth",
    type: "CALL",
    strikePrice: 130,
    quantity: 500,
    premium: 8,
    expiry: "2026-07-01",
    seller: "0xCCDD...EEF0",
    status: "OPEN",
    created: "2026-04-01",
  },
  {
    id: "c005",
    resourceId: "titanium",
    type: "PUT",
    strikePrice: 10500,
    quantity: 10,
    premium: 320,
    expiry: "2026-10-31",
    seller: "0x9988...7766",
    status: "OPEN",
    created: "2026-03-30",
  },
];

export { RESOURCES, CATEGORIES, SEED_CONTRACTS };
